### ISSUE TITLE
[Feature request] Ability to start interactive jobs (like a reverse SSH)

### ISSUE THREAD

**Issue by reuben** [mozilla/snakepit-client#10]
For interactive tasks that require big compute, like evaluating a model after it's trained it'd be nice to have the ability to start a shell in the cluster as a job so you can run interactive tasks without sending tons of little jobs. This would also speed up the edit-run cycle since you don't have to wait for (mostly) the same code to be submitted every time.

**Comment by tilmankamp** [comment]
`pit exec` covers most of this in conjunction with something like `pit run "Interactive" [] -d 'sleep infinity'`. There are tickets for interactive/auto-deleting jobs in https://github.com/mozilla/snakepit project.
