### ISSUE TITLE
Can't submit job from private repository

### ISSUE THREAD

**Issue by reuben** [mozilla/snakepit-client#12]
Error:         "Problem during preparation step - exit code: 128
Cloning into '/snakepit/cache/9c46e2d4b9e28a46f64ccb96bd3b043b'...

fatal: could not read Username for 'https://github.com': No such device or address"

**Comment by tilmankamp** [comment]
This is (intentionally) not supported. One should use archive based job upload (`pit run --archive ...`) for this.
