### ISSUE TITLE
[Feature Request] Report download size when using `pit download`

### ISSUE THREAD

**Issue by reuben** [mozilla/snakepit-client#15]
A progress report would also be nice.

**Comment by reuben** [comment]
Looks like the response from the server doesn't include a Content-Length. Maybe something like this would allow for it to be reported on the client side: https://gist.github.com/reuben/401d28ef76186709cdbc6cd05b6ed69f

**Comment by tilmankamp** [comment]
Superseded by `pit exec <job> -- ls -la <path/to/file>` for querying the size and `pit pull` (showing download speed/ETA) for retrieving it.
