### ISSUE TITLE
pit run -d only works from git repo

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/snakepit-client#26]
@tilmankamp --- not sure if this is desired behavior, but `pit run -d` only works from within a valid git repo

I should think the command can be run anywhere

```
josh@carbon:~$ pit run "ENV VARS" [] -d 'sudo apt-get install tree; tree $SHARED_DIR'
Command failed: Problem getting remote branch "origin/master"
```

**Comment by tilmankamp** [comment]
Great idea!

**Comment by JRMeyer** [comment]
@tilmankamp this is a ping

I've been trying to run `pit run "LS" [] -d 'ls $SHARED_DIR'` and it keeps failing at `git pull`.

As you know, what I'm trying to do is look at the server, and I don't care about which branch I'm on... but with `snakepit` this is impossible if I have a local branch that isn't pushed up to Github.

I'm realizing there's two things I want to do with `snakepit`:

1. run `deepspeech` training jobs
2. use `snakepit` as a substitute for `ssh` to work on server

For you and @kdavis-mozilla, you use `snakepit` for only running jobs, and you actually use `ssh` itself when it comes to working on the server. 

Using `snakepit` as a substitute for `ssh` *really* slows down my workflow when I have to do anything on the server. I suggest either we make `snakepit` have more `ssh`-like functionality, or give me `ssh` access with certain permissions. Otherwise I have to ask @kdavis-mozilla to do simple file manipulations in my place, and he has better things to do.

**Comment by tilmankamp** [comment]
`pit exec RUNNING_JOB -- bash` should allow for doing most if not all of this now. The `--execute|-e` flag (formerly known as `-d` flag that is now responsible for debugging) is also supported for non-repository aka archive based jobs.
