### ISSUE TITLE
Feature Request: Specify which node to run job on

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/snakepit-client#29]
if this is possible, it's not documented.

I'd like to run this:

```
pit run "2 txp's on node MLC3" mlc3:[2:txp]
```

**Comment by kdavis-mozilla** [comment]
I don't think this is a good idea.

The scheduler knows which nodes are under utilized and make the decision as to where to place jobs.

**Comment by JRMeyer** [comment]
The motivation behind this comes from my experience yesterday, when `mlc0` was obviously not working, while `mlc3` was. I could run _any_ job on `mlc3`, while _every_ `mlc0` job crashed.

Every job I sent to `mlc0` ended with an error of `dkpg lock` as reported here[[1](https://github.com/mozilla/snakepit/issues/140)].

Given that both `mlc0` and `mlc3` had no jobs, any job I sent went first to `mlc0`. My work around was to send an 8-GPU job to `mlc0`, and quickly send of my intended job to `mlc3` before the 8-GPU job crashed.

**Comment by tilmankamp** [comment]
Machines could get targeted through groups (if configured accordingly).
