### ISSUE TITLE
`pit ls home` results in 502 Bad Gateway

### ISSUE THREAD

**Issue by reuben** [mozilla/snakepit-client#38]
pit --debug ls home
    SENDING get https://e.example:443/users/~/simplefs/stats/
    RECEIVING CODE 200
    - BODY { isFile: false,
      size: 4096,
      mtime: '2019-09-12T14:07:13.218Z',
      atime: '2019-10-08T08:34:16.900Z',
      ctime: '2019-09-12T14:07:13.218Z' }
    SENDING get https://e.example:443/users/~/simplefs/content/
    RECEIVING CODE 502
    Command failed: Bad Gateway

Same happens for `pit ls user:rmorais` for me.

**Comment by tilmankamp** [comment]
This is typically caused by the/a front-end web-server having timeouts talking to the back-end service (in this case snakepit). Was not able to reproduce (now). Please note down the exact point in time and message me, once this re-occurs.

**Comment by reuben** [comment]
I can still reproduce it...

Tue Oct  8 11:30:17 CEST 2019

**Comment by reuben** [comment]
Note that it's only `home` and `user:rmorais` that does this. Other entities like job numbers and `group:ml` work fine.

**Comment by tilmankamp** [comment]
Ah - OK it indeed fails with your user and you got some strange files in your home. Could be an error on the FS routines that let the front-end timeout - investigating...

**Comment by tilmankamp** [comment]
Result of https://github.com/mozilla/snakepit/issues/177
