### ISSUE TITLE
pit push and pit cp to/from non-networked folder in worker

### ISSUE THREAD

**Issue by reuben** [mozilla/snakepit-client#39]
`pit push` and `pit cp` don't let you push to e.g. /tmp on a worker, which means you have to push and then move/copy the data. It'd be nice if you could interact directly with the FS in the worker.

**Comment by tilmankamp** [comment]
You should be able to 
- push via `cat LOCAL_FILE | pit exec JOB -- 'tee >REMOTE_FILE'` and to 
- pull via `pit exec JOB -- cat REMOTE_FILE >LOCAL_FILE`.
