### ISSUE TITLE
`pit exec` merges stdout and stderr from remote process

### ISSUE THREAD

**Issue by reuben** [mozilla/snakepit-client#40]
When trying to use e.g. DeepSpeech's bin/play.py over `pit exec` to extract an audio file from an SDB, you have to use `--quiet` otherwise pit will send remote stdout and remote stderr to local stdout and merge the information messages with the audio data.

**Comment by tilmankamp** [comment]
I think this has a different reason, as `process.stdout` and `process.stderr` streams are already handled separately: https://github.com/mozilla/snakepit-client/blob/39937f90e700cfc48d12983c2983fc08e0972844/src/pit.js#L1361-L1367

**Comment by tilmankamp** [comment]
With recent changes I am now able to use `play.py` without `--quiet` flag.
