### ISSUE TITLE
`pit exec` interactive mode detection should also check stdout

### ISSUE THREAD

**Issue by reuben** [mozilla/snakepit-client#41]
Doing this:

```pit exec 5880 -- /tmp/venv/bin/python /data/rw/pit/keep/DeepSpeech/bin/play.py /data/rw/group-ml/ds/mandarin/oi_mandarin_collection/train.sdb --start 283141 --pipe --quiet > a.wav```

Leads to a corrupted `a.wav` file. (Compared to running the command in a shell on the job and then using `pit cp` to copy the file).

Doing this:

```
echo yes | pit exec 5880 -- /tmp/venv/bin/python /data/rw/pit/keep/DeepSpeech/bin/play.py /data/rw/group-ml/ds/mandarin/oi_mandarin_collection/train.sdb --start 283141 --pipe --quiet > raw_mode.wav
```

Leads to a correct `raw_mode.wav` matching the one on the remote. I think it's because the client is only checking stdin to test for interactive mode? And then it inserts control codes in the output or something. I can't quite pinpoint the nature of the corruption in the data.

**Comment by reuben** [comment]
Simpler repro with just `cat`:

```
$ pit exec 5880 -- sha256sum /data/rw/pit/keep/DeepSpeech/a.wav
f59c0dd0449c18440ad4a1f6f070702c77d082c4a36f7bc8fbbc7da3532a310c  /data/rw/pit/keep/DeepSpeech/a.wav
$ pit exec 5880 -- cat /data/rw/pit/keep/DeepSpeech/a.wav > cat.wav
$ shasum -a 256 cat.wav
4099a1fb5baec8f3e8e5f4b0df8959017d7ea50fca7da448c4d9d0d242a972a6  cat.wav
```

**Comment by reuben** [comment]
Testing with a text file, it looks like carriage returns are being added, every `\n` gets replaced with `\r\r\n`.

**Comment by reuben** [comment]
Adding some logging I think the problem is that the server is sending strings instead of binary data, and then whitespace gets mangled. And the fact that there's multiple carriage returns being added suggests that this is happening more than once in the client -> server -> LXD socket chain.

**Comment by tilmankamp** [comment]
`pit exec 5880 -- /tmp/venv/bin/python /data/rw/pit/keep/DeepSpeech/bin/play.py /data/rw/group-ml/ds/mandarin/oi_mandarin_collection/train.sdb --start 283141 --pipe > raw_mode.wav` should work now (mind the missing `--quiet` flag).

You could also use SoX's `play` command:
`pit exec 5880 -- /tmp/venv/bin/python /data/rw/pit/keep/DeepSpeech/bin/play.py /data/rw/group-ml/ds/mandarin/oi_mandarin_collection/train.sdb --start 283141 --pipe | play -q -`
